version = 1

[logger]
level = 1
thread = true
show_flag = 0x03
log_rolling_size = 10485760 # 10MB

[file]
log_dir = "./"
log_file = "log_xlib.log"
#timestamp =
#log_name = "log_test_${time}_${counter}"
